export enum AccessControlErrorCode {
  // User profile and permissions errors
  // USER_PROFILE_NOT_FOUND removed - use UserProfileErrors.userProfileNotFound() instead
  USER_ACCESS_NOT_FOUND = 'ACL_025',
  USER_ALREADY_HAS_ACCESS = 'ACL_002',

  // Center access errors
  CENTER_ACCESS_NOT_FOUND = 'ACL_003',
  CENTER_ACCESS_ALREADY_EXISTS = 'ACL_004',
  CENTER_ACCESS_ALREADY_DELETED = 'ACL_005',
  CENTER_ACCESS_ALREADY_INACTIVE = 'ACL_006',

  // Role and permission errors
  ROLE_NOT_FOUND = 'ACL_007',
  ROLE_ALREADY_EXISTS = 'ACL_008',
  PERMISSION_NOT_FOUND = 'ACL_009',
  PERMISSION_ALREADY_ASSIGNED = 'ACL_010',

  // Assignment and management errors
  CANNOT_ASSIGN_ROLE_TO_SELF = 'ACL_011',
  USER_ALREADY_HAS_ROLE = 'ACL_013',
  USER_DOES_NOT_HAVE_ROLE = 'ACL_014',

  // Status and state errors
  CANNOT_MODIFY_SYSTEM_ROLE = 'ACL_015',
  INVALID_PROFILE_TYPE_FOR_ROLE_ASSIGNMENT = 'ACL_018',
  ROLE_ALREADY_ACTIVE = 'ACL_019',
  UNSUPPORTED_PROFILE_TYPE_FOR_CENTER_ACCESS = 'ACL_020',
  CANNOT_DELETE_ADMIN_CENTER_ACCESS = 'ACL_021',
  CANNOT_RESTORE_ACTIVE_CENTER_ACCESS = 'ACL_022',
  CANNOT_MODIFY_ADMIN_CENTER_ACCESS = 'ACL_023',
  INVALID_PROFILE_TYPE = 'ACL_024',

  // Access control errors
  CANNOT_ACCESS_GRANTER_USER = 'ACL_026',
  CANNOT_ACCESS_TARGET_USER = 'ACL_027',
  CANNOT_REVOKE_USER_ACCESS = 'ACL_028',
  CANNOT_ACCESS_USER_RECORDS = 'ACL_029',
  MISSING_PERMISSION = 'ACL_030',

  // Inactive entity errors
  CENTER_ACCESS_INACTIVE = 'ACL_031',

  // Role hierarchy errors
  CANNOT_OPERATE_ON_HIGHER_ROLE = 'ACL_032',
}
