export enum ErrorCode {
  // Authentication & Authorization
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  ACCESS_DENIED = 'ACCESS_DENIED',
  PHONE_NOT_VERIFIED = 'PHONE_NOT_VERIFIED',
  OTP_REQUIRED = 'OTP_REQUIRED',
  ADMIN_SCOPE_ACCESS_DENIED = 'ADMIN_SCOPE_ACCESS_DENIED',
  CENTER_SELECTION_REQUIRED = 'CENTER_SELECTION_REQUIRED',
  CENTER_ACCESS_DENIED = 'CENTER_ACCESS_DENIED',
  CENTER_ACCESS_INACTIVE = 'CENTER_ACCESS_INACTIVE',
  CENTER_INACTIVE = 'CENTER_INACTIVE',
  PROFILE_INACTIVE = 'PROFILE_INACTIVE',
  BRANCH_ACCESS_DENIED = 'BRANCH_ACCESS_DENIED',
  PROFILE_SELECTION_REQUIRED = 'PROFILE_SELECTION_REQUIRED',

  // Validation & Input
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
  INVALID_OPERATION = 'INVALID_OPERATION',
  BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
  SCHEDULE_CONFLICT_ERROR = 'SCHEDULE_CONFLICT_ERROR',
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  DUPLICATE_FIELD = 'DUPLICATE_FIELD',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',

  // Resource Management
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_IN_USE = 'RESOURCE_IN_USE',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  CENTER_NOT_FOUND = 'CENTER_NOT_FOUND',
  BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND',

  // Server Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SYSTEM_NOT_READY = 'SYSTEM_NOT_READY',

  // Database Errors
  FOREIGN_KEY_CONSTRAINT_VIOLATION = 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
  TABLE_NOT_FOUND = 'TABLE_NOT_FOUND',
  QUERY_FAILED = 'QUERY_FAILED',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  SEEDER_ERROR = 'SEEDER_ERROR',

  // Export & File Operations
  EXPORT_FORMAT_NOT_SUPPORTED = 'EXPORT_FORMAT_NOT_SUPPORTED',
  EXPORT_DATA_UNAVAILABLE = 'EXPORT_DATA_UNAVAILABLE',
  EXPORT_FAILED = 'EXPORT_FAILED',

  // Request Validation
  MISSING_REQUIRED_HEADER = 'MISSING_REQUIRED_HEADER',
  INVALID_CONTENT_TYPE = 'INVALID_CONTENT_TYPE',
  REQUEST_BODY_TOO_LARGE = 'REQUEST_BODY_TOO_LARGE',
  UNSUPPORTED_CONTENT_TYPE = 'UNSUPPORTED_CONTENT_TYPE',

  // Generic HTTP Status Codes
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
