export enum ErrorCode {
  // Authentication & Authorization
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  ACCESS_DENIED = 'ACCESS_DENIED',
  ADMIN_SCOPE_ACCESS_DENIED = 'ADMIN_SCOPE_ACCESS_DENIED',
  CENTER_SELECTION_REQUIRED = 'CENTER_SELECTION_REQUIRED',
  CENTER_ACCESS_DENIED = 'CENTER_ACCESS_DENIED',

  // Validation & Input
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
  INVALID_OPERATION = 'INVALID_OPERATION',
  BUSINESS_LOGIC_ERROR = 'BUSINESS_LOGIC_ERROR',
  REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
  DUPLICATE_FIELD = 'DUPLICATE_FIELD',

  // Resource Management
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_IN_USE = 'RESOURCE_IN_USE',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Server Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Database Errors
  FOREIGN_KEY_CONSTRAINT_VIOLATION = 'FOREIGN_KEY_CONSTRAINT_VIOLATION',
  TABLE_NOT_FOUND = 'TABLE_NOT_FOUND',
  QUERY_FAILED = 'QUERY_FAILED',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',

  // Generic HTTP Status Codes
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
