// Auto-generated. Do not edit.
// This file is generated by scripts/generate-template-types.ts
// Run 'npm run generate:templates' to regenerate

export type NotificationTemplatePath =
  | 'email/auth/email-verification'
  | 'email/auth/otp'
  | 'email/auth/password-reset'
  | 'email/center-created'
  | 'email/center-updated'
  | 'email/default'
  | 'in-app/auth/email-verification'
  | 'in-app/auth/otp'
  | 'in-app/auth/password-reset'
  | 'in-app/center-created'
  | 'in-app/center-updated'
  | 'in-app/default'
  | 'sms/auth/email-verification'
  | 'sms/auth/otp'
  | 'sms/auth/password-reset'
  | 'sms/center-created'
  | 'sms/center-updated'
  | 'sms/default'
  | 'whatsapp/auth/email-verification'
  | 'whatsapp/auth/otp'
  | 'whatsapp/auth/password-reset'
  | 'whatsapp/center-created'
  | 'whatsapp/center-updated'
  | 'whatsapp/default';

export type TemplateBasePath =
  | 'auth/email-verification'
  | 'auth/otp'
  | 'auth/password-reset'
  | 'center-created'
  | 'center-updated'
  | 'default';
