export enum NotificationType {
  // Auth & Security notifications
  OTP = 'OTP',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Center notifications
  CENTER_CREATED = 'CENTER_CREATED',
  CENTER_UPDATED = 'CENTER_UPDATED',
}
