export enum NotificationType {
  // Auth & Security notifications
  OTP = 'OTP',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  NEW_DEVICE_LOGIN = 'NEW_DEVICE_LOGIN',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  LOGIN_FAILED = 'LOGIN_FAILED',
  TWO_FA_DISABLED = 'TWO_FA_DISABLED',

  // Center notifications
  CENTER_CREATED = 'CENTER_CREATED',
  CENTER_UPDATED = 'CENTER_UPDATED',
  CENTER_DELETED = 'CENTER_DELETED',
  CENTER_RESTORED = 'CENTER_RESTORED',

  // Branch notifications
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_UPDATED = 'BRANCH_UPDATED',
  BRANCH_DELETED = 'BRANCH_DELETED',
  BRANCH_RESTORED = 'BRANCH_RESTORED',

  // Access Control notifications
  CENTER_ACCESS_ACTIVATED = 'CENTER_ACCESS_ACTIVATED',
  CENTER_ACCESS_DEACTIVATED = 'CENTER_ACCESS_DEACTIVATED',
  CENTER_ACCESS_GRANTED = 'CENTER_ACCESS_GRANTED',
  CENTER_ACCESS_REVOKED = 'CENTER_ACCESS_REVOKED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REVOKED = 'ROLE_REVOKED',

  // Session notifications
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_UPDATED = 'SESSION_UPDATED',
  SESSION_CANCELED = 'SESSION_CANCELED',
  SESSION_FINISHED = 'SESSION_FINISHED',
  SESSION_DELETED = 'SESSION_DELETED',
  SESSION_CHECKED_IN = 'SESSION_CHECKED_IN',
  SESSION_CONFLICT_DETECTED = 'SESSION_CONFLICT_DETECTED',

  // Class notifications
  CLASS_CREATED = 'CLASS_CREATED',
  CLASS_UPDATED = 'CLASS_UPDATED',
  CLASS_DELETED = 'CLASS_DELETED',
  CLASS_STATUS_CHANGED = 'CLASS_STATUS_CHANGED',
  STAFF_ASSIGNED_TO_CLASS = 'STAFF_ASSIGNED_TO_CLASS',
  STAFF_REMOVED_FROM_CLASS = 'STAFF_REMOVED_FROM_CLASS',

  // Group notifications
  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_UPDATED = 'GROUP_UPDATED',
  GROUP_DELETED = 'GROUP_DELETED',
  STUDENT_ADDED_TO_GROUP = 'STUDENT_ADDED_TO_GROUP',
  STUDENT_REMOVED_FROM_GROUP = 'STUDENT_REMOVED_FROM_GROUP',

  // Attendance notifications
  STUDENT_ABSENT = 'STUDENT_ABSENT',

  // Student billing notifications
  CHARGE_COMPLETED = 'CHARGE_COMPLETED',
  CHARGE_INSTALLMENT_PAID = 'CHARGE_INSTALLMENT_PAID',
  CHARGE_REFUNDED = 'CHARGE_REFUNDED',

  // Teacher payout notifications
  PAYOUT_CREATED = 'PAYOUT_CREATED',
  PAYOUT_PAID = 'PAYOUT_PAID',
  PAYOUT_INSTALLMENT_PAID = 'PAYOUT_INSTALLMENT_PAID',

  // Expense notifications
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_REFUNDED = 'EXPENSE_REFUNDED',

  // User profile lifecycle
  USER_PROFILE_ACTIVATED = 'USER_PROFILE_ACTIVATED',
  USER_PROFILE_DEACTIVATED = 'USER_PROFILE_DEACTIVATED',
  USER_PROFILE_DELETED = 'USER_PROFILE_DELETED',
  USER_PROFILE_RESTORED = 'USER_PROFILE_RESTORED',
  USER_PROFILE_CREATED = 'USER_PROFILE_CREATED',
}
