/**
 * Session-related error codes (SES_xxx)
 * Range: SES_001 - SES_099
 */
export enum SessionErrorCode {
  SESSION_NOT_FOUND = 'SES_001',
  SESSION_ALREADY_EXISTS = 'SES_002',
  SESSION_INACTIVE = 'SES_003',
  SESSION_DELETED = 'SES_004',
  SESSION_STATUS_TRANSITION_INVALID = 'SES_005',
  SESSION_CANNOT_MODIFY_COMPLETED = 'SES_006',
  SESSION_CANNOT_MODIFY_CANCELLED = 'SES_007',
  SESSION_START_TIME_PAST = 'SES_008',
  SESSION_CANCEL_FAILED = 'SES_017',
  SESSION_CLASS_NOT_ACTIVE = 'SES_019',
  SESSION_SCHEDULE_CONFLICT = 'SES_020',
  SESSION_CHECK_IN_INVALID_STATUS = 'SES_021',
  SESSION_SCHEDULE_ITEM_NOT_FOUND = 'SES_022',
  SESSION_NOT_CHECKED_IN = 'SES_023',
  SESSION_START_INVALID_STATUS = 'SES_024',
  SESSION_CANNOT_UPDATE = 'SES_025',
  SESSION_STATUS_INVALID_FOR_OPERATION = 'SES_026',
  SESSION_ACCESS_DENIED = 'SES_027',
  SESSION_SCHEDULE_ITEM_INVALID = 'SES_028',
  SESSION_INVALID_ID_FORMAT = 'SES_029',
}
