export enum ClassActivityType {
  CLASS_CREATED = 'CLASS_CREATED',
  CLASS_UPDATED = 'CLASS_UPDATED',
  CLASS_DELETED = 'CLASS_DELETED',
  CLASS_RESTORED = 'CLASS_RESTORED',
  CLASS_EXPORTED = 'CLASS_EXPORTED',
}
