export enum ClassStatus {
  PENDING_TEACHER_APPROVAL = 'PENDING_TEACHER_APPROVAL',
  NOT_STARTED = 'NOT_STARTED',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
}

