export enum ClassErrorCode {
  // Class existence and lookup errors
  CLASS_NOT_FOUND = 'CLS_001',
  CLASS_ALREADY_EXISTS = 'CLS_002',

  // Class status and lifecycle errors
  CLASS_STATUS_TRANSITION_INVALID = 'CLS_005',
  CLASS_CANNOT_MODIFY_COMPLETED = 'CLS_006',
  CLASS_CANNOT_MODIFY_CANCELLED = 'CLS_007',
  CLASS_STATUS_CHANGE_GRACE_PERIOD_EXPIRED = 'CLS_008',

  // Class access and permissions
  CLASS_ACCESS_DENIED = 'CLS_029',
  CANNOT_ACCESS_CLASSES = 'CLS_056',
  CANNOT_ACCESS_CLASS = 'CLS_057',
  CLASS_STAFF_ALREADY_ASSIGNED = 'CLS_031',
  CLASS_STAFF_NOT_ASSIGNED = 'CLS_032',

  // Payment strategy errors
  PAYMENT_STRATEGY_NOT_FOUND = 'CLS_033',
  PAYMENT_STRATEGY_UPDATE_DENIED = 'CLS_034',

  // Schedule errors
  SCHEDULE_CONFLICT = 'CLS_036',
  SCHEDULE_OVERLAP = 'CLS_037',
  TEACHER_SCHEDULE_CONFLICT = 'CLS_038',
  STUDENT_SCHEDULE_CONFLICT = 'CLS_041',

  // Group errors
  GROUP_NOT_FOUND = 'CLS_039',
  GROUP_ALREADY_EXISTS = 'CLS_040',
  GROUP_STUDENT_ALREADY_ASSIGNED = 'CLS_044',
  GROUP_STUDENT_NOT_ASSIGNED = 'CLS_045',
  STUDENT_INVALID_TYPE_FOR_GROUP_ASSIGNMENT = 'CLS_052',
  STUDENT_ALREADY_ASSIGNED_TO_GROUP = 'CLS_053',
  RESOURCE_ACCESS_DENIED = 'CLS_054',
  CLASS_STAFF_ACCESS_NOT_FOUND = 'CLS_055',

  // Validation errors
  CLASS_VALIDATION_FAILED = 'CLS_046',
  GROUP_VALIDATION_FAILED = 'CLS_047',
  CLASS_START_DATE_UPDATE_FORBIDDEN = 'CLS_048',
  CLASS_STATUS_DOES_NOT_ALLOW_STAFF_ASSIGNMENT = 'CLS_049',
  STAFF_ALREADY_ASSIGNED_TO_CLASS = 'CLS_050',
  GROUP_CREATION_NOT_ALLOWED_FOR_CLASS_STATUS = 'CLS_051',
  CLASS_BRANCH_REQUIRED = 'CLS_058',
}
