export enum GroupActivityType {
  GROUP_CREATED = 'GROUP_CREATED',
  GROUP_UPDATED = 'GROUP_UPDATED',
  GROUP_DELETED = 'GROUP_DELETED',
  GROUP_RESTORED = 'GROUP_RESTORED',
  GROUP_EXPORTED = 'GROUP_EXPORTED',
}
