export enum CentersErrorCode {
  // Branch errors
  BRANCH_NOT_FOUND = 'CTR_BRN_001',

  // Center errors
  CENTER_NOT_FOUND = 'CTR_CTR_001',
  CENTER_ALREADY_EXISTS = 'CTR_CTR_002',
  CENTER_ALREADY_ACTIVE = 'CTR_CTR_003',

  // Branch access errors
  BRANCH_ACCESS_NOT_FOUND = 'CTR_ACC_004',
  BRANCH_ACCESS_DENIED = 'CTR_ACC_001',
  BRANCH_ACCESS_ALREADY_GRANTED = 'CTR_ACC_002',
  BRANCH_ACCESS_NOT_GRANTED = 'CTR_ACC_003',

  // Profile/assignment errors
  PROFILE_INVALID_TYPE_FOR_BRANCH_ACCESS = 'CTR_PRF_001',
  PROFILE_ALREADY_HAS_BRANCH_ACCESS = 'CTR_PRF_002',

  // Validation errors
  BRANCH_VALIDATION_FAILED = 'CTR_VAL_001',
  CENTER_VALIDATION_FAILED = 'CTR_VAL_002',
  CENTER_ID_REQUIRED = 'CTR_VAL_003',

  // Inactive entity errors
  CENTER_INACTIVE = 'CTR_CTR_004',
  BRANCH_INACTIVE = 'CTR_BRN_002',
}
