export enum FinanceErrorCode {
  // Payment and wallet errors
  WALLET_NOT_FOUND = 'FIN_PAY_002',
  CASHBOX_NOT_FOUND = 'FIN_PAY_003',
  PAYMENT_PROVIDER_DOWN = 'FIN_PAY_004',
  TRANSACTION_FAILED = 'FIN_PAY_005',

  // Transfer-specific errors
  TRANSFER_PROFILES_DIFFERENT_USERS = 'FIN_XFER_001',
  TRANSFER_SAME_PROFILE = 'FIN_XFER_002',

  // Transaction-specific errors
  TRANSACTION_NOT_FOUND = 'FIN_TXN_001',
  TRANSACTION_AMOUNT_MISMATCH = 'FIN_TXN_002',
  TRANSACTION_BALANCE_REQUIRED = 'FIN_TXN_003',
  CASH_TRANSACTION_NOT_FOUND = 'FIN_CTXN_001',

  // Payment-specific errors
  PAYMENT_REFERENCE_INVALID = 'FIN_PAY_006',
  PAYMENT_NOT_COMPLETED = 'FIN_PAY_007',
  PAYMENT_ALREADY_REFUNDED = 'FIN_PAY_008',
  PAYMENT_NOT_PENDING = 'FIN_PAY_009',
  PAYMENT_CURRENCY_NOT_SUPPORTED = 'FIN_PAY_010',
  PAYMENT_SERVICE_UNAVAILABLE = 'FIN_PAY_011',
  PAYMENT_SETUP_FAILED = 'FIN_PAY_012',
  PAYMENT_PROCESSING_FAILED = 'FIN_PAY_013',
  PAYMENT_NOT_FOUND_BY_GATEWAY_ID = 'FIN_PAY_014',
  PAYMENT_NOT_REFUNDABLE = 'FIN_PAY_015',
  PAYMENT_NOT_EXTERNAL = 'FIN_PAY_016',
  REFUND_AMOUNT_EXCEEDS_PAYMENT = 'FIN_PAY_017',
  PAYMENT_MISSING_GATEWAY_ID = 'FIN_PAY_018',
  INSUFFICIENT_REFUND_BALANCE = 'FIN_PAY_019',
  PAYMENT_STATUS_TRANSITION_INVALID = 'FIN_PAY_020',
  PAYMENT_OVERRIDE_DENIED = 'FIN_PAY_021',
  PAYMENT_OWNERSHIP_REQUIRED = 'FIN_PAY_022',
  WALLET_ACCESS_DENIED = 'FIN_PAY_023',

  // Payment execution errors
  PAYMENT_EXECUTION_FAILED = 'FIN_PAY_024',
  INVALID_PAYMENT_AMOUNT = 'FIN_PAY_025',
  INVALID_PAYMENT_DATA = 'FIN_PAY_026',
  UNSUPPORTED_PAYMENT_SOURCE = 'FIN_PAY_027',
  PAYMENT_ALREADY_EXISTS = 'FIN_PAY_028',
  INSUFFICIENT_WALLET_BALANCE = 'FIN_PAY_029',
  INSUFFICIENT_CASH_BALANCE = 'FIN_PAY_030',
  INVALID_CASH_PAYMENT_CONFIGURATION = 'FIN_PAY_031',
  PAYMENT_NOT_FOUND = 'FIN_PAY_032',
  INVALID_PAYMENT_OPERATION = 'FIN_PAY_033',

  // General finance errors
  // (No generic errors - use specific codes)
}
