export enum PaymentReason {
  SESSION = 'SESSION',
  SUBSCRIPTION = 'SUBSCRIPTION',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  WITHDRAWAL = 'WITHDRAWAL',
  TOPUP = 'TOPUP',
  PACKAGE_PURCHASE = 'PACKAGE_PURCHASE',
  SESSION_BOOKING = 'SESSION_BOOKING',
}

