export enum PaymentReason {
  // Student fees
  SESSION_FEE = 'SESSION_FEE',
  MONTHLY_FEE = 'MONTHLY_FEE',
  CLASS_FEE = 'CLASS_FEE',

  // Teacher payouts
  TEACHER_STUDENT_PAYOUT = 'TEACHER_STUDENT_PAYOUT',
  TEACHER_HOUR_PAYOUT = 'TEACHER_HOUR_PAYOUT',
  TEACHER_SESSION_PAYOUT = 'TEACHER_SESSION_PAYOUT',
  TEACHER_MONTHLY_PAYOUT = 'TEACHER_MONTHLY_PAYOUT',
  TEACHER_CLASS_PAYOUT = 'TEACHER_CLASS_PAYOUT',

  // System operations
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  TOPUP = 'TOPUP',

  // Branch operations
  BRANCH_WITHDRAWAL = 'BRANCH_WITHDRAWAL',
  BRANCH_DEPOSIT = 'BRANCH_DEPOSIT',
}
