export enum PaymentReferenceType {
  TRANSACTION = 'TRANSACTION',
  CASH_TRANSACTION = 'CASH_TRANSACTION',
  ENROLLMENT = 'ENROLLMENT',
  GATEWAY_PAYMENT = 'GATEWAY_PAYMENT',
  TEACHER_PAYOUT = 'TEACHER_PAYOUT',
}
