export enum PaymentReason {
  SESSION = 'SESSION',
  SUBSCRIPTION = 'SUBSCRIPTION',
  CLASS = 'CLASS',
  TEACHER_PAYOUT = 'TEACHER_PAYOUT',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  WITHDRAWAL = 'WITHDRAWAL',
  TOPUP = 'TOPUP',
}
