export enum TransactionType {
  STUDENT_PAYMENT = 'STUDENT_PAYMENT',
  BRANCH_COLLECTION = 'BRANCH_COLLECTION',
  TEACHER_SALARY = 'TEACHER_SALARY',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  TOPUP = 'TOPUP',
  REFUND = 'REFUND',
  SESSION_PAYMENT = 'SESSION_PAYMENT',
  MONTHLY_PAYMENT = 'MONTHLY_PAYMENT',
}
