export enum AuthActivityType {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_SIGNUP = 'USER_SIGNUP',
  USER_LOGOUT = 'USER_LOGOUT',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PHONE_VERIFIED = 'PHONE_VERIFIED',
  TWO_FA_SETUP = 'TWO_FA_SETUP',
  TWO_FA_ENABLED = 'TWO_FA_ENABLED',
  TWO_FA_DISABLED = 'TWO_FA_DISABLED',
}
