/**
 * Student Billing-related error codes (SBL_xxx)
 * Range: SBL_001 - SBL_049
 */
export enum StudentBillingErrorCode {
  SUBSCRIPTION_PAYMENT_STRATEGY_MISSING = 'SBL_001',
  SUBSCRIPTION_ALREADY_EXISTS = 'SBL_002',
  SUBSCRIPTION_INVALID_PAYMENT_SOURCE = 'SBL_003',
  SESSION_CHARGE_PAYMENT_STRATEGY_MISSING = 'SBL_004',
  SESSION_CHARGE_ALREADY_EXISTS = 'SBL_005',
  SESSION_CHARGE_INVALID_PAYMENT_SOURCE = 'SBL_006',
  MONTHLY_SUBSCRIPTIONS_NOT_ALLOWED = 'SBL_007',
  SESSION_CHARGES_NOT_ALLOWED = 'SBL_008',
  SESSION_PAYMENTS_NOT_CONFIGURED = 'SBL_009',
  MONTHLY_PAYMENTS_NOT_CONFIGURED = 'SBL_010',
  CLASS_CHARGES_NOT_ALLOWED = 'SBL_011',
  CLASS_PAYMENTS_NOT_CONFIGURED = 'SBL_012',
  CLASS_CHARGE_ALREADY_EXISTS = 'SBL_013',

  // Refund errors
  BILLING_RECORD_NOT_FOUND = 'SBL_014',
  REFUND_VALIDATION_FAILED = 'SBL_015',
  ALREADY_REFUNDED = 'SBL_016',
  REFUND_FAILED = 'SBL_017',
  REFUND_UNSUPPORTED_PAYMENT_TYPE = 'SBL_018',
  REFUND_PAYMENT_NOT_FOUND = 'SBL_019',

  // Installment payment errors
  CLASS_CHARGE_NOT_FOUND = 'SBL_020',
  CLASS_ALREADY_FULLY_PAID = 'SBL_021',
  INVALID_CHARGE_STATUS = 'SBL_022',
  PAYMENT_EXCEEDS_TOTAL_AMOUNT = 'SBL_023',
}
