/**
 * Student Billing-related error codes (SBL_xxx)
 * Range: SBL_001 - SBL_049
 */
export enum StudentBillingErrorCode {
  SUBSCRIPTION_PAYMENT_STRATEGY_MISSING = 'SBL_001',
  SUBSCRIPTION_ALREADY_EXISTS = 'SBL_002',
  SUBSCRIPTION_INVALID_PAYMENT_SOURCE = 'SBL_003',
  SESSION_CHARGE_PAYMENT_STRATEGY_MISSING = 'SBL_004',
  SESSION_CHARGE_ALREADY_EXISTS = 'SBL_005',
  SESSION_CHARGE_INVALID_PAYMENT_SOURCE = 'SBL_006',
}
